# Generated by Django 6.0.4 on 2026-09-01 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('country', models.CharField(default='Inconnu', max_length=100)),
                ('visits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Visite journalière',
                'verbose_name_plural': 'Visites journalières',
                'unique_together': {('date', 'country')},
            },
        ),
    ]
