# Generated by Django 6.0.5 on 2026-06-10 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_reference', models.CharField(blank=True, help_text='ID de la transaction généré par le prestataire de paiement', max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant exact tenté lors de cette transaction', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESSFUL', 'Réussie'), ('FAILED', 'Échouée'), ('CANCELED', 'Annulée')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('STRIPE', 'Stripe'), ('CINETPAY', 'CinetPay'), ('WAVE', 'Wave'), ('PAYPAL', 'PayPal')], default='STRIPE', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur renvoyé par la banque en cas d'échec", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ecommerce.order')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
