# Generated by Django 6.0.4 on 2026-06-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('CINETPAY', 'CinetPay'), ('WAVE', 'Wave'), ('PAYPAL', 'PayPal'), ('SIMULATED', 'Simulation')], default='STRIPE', max_length=20),
        ),
    ]
