# Generated by Django 6.0.4 on 2026-06-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('CINETPAY', 'CinetPay'), ('WAVE', 'Wave'), ('OMCIV2', 'Orange Ci'), ('FLOOZ', 'Moov Ci'), ('MOMOCI', 'Mtn Ci'), ('OMBF', 'Orange Bf'), ('OMML', 'Orange Mali'), ('MOMOBJ', 'Mtn Benin'), ('CARD', 'Visa Mastercard'), ('FLOOZBJ', 'Moov Benin'), ('AIRTELNG', 'Airtel Niger'), ('WAVECI', 'Wave Ci'), ('OMSN', 'Orange Senegal'), ('OMGN', 'Orange Guinee Bissau'), ('OMCM', 'Orange Cameroun'), ('WAVESN', 'Wave Senegal'), ('MOOTG', 'Flooz Togo'), ('TOGOCEL', 'Togo Cel'), ('MOMOCM', 'Mtn Cameroun'), ('PAYPAL', 'PayPal'), ('SIMULATED', 'Simulation')], default='STRIPE', max_length=20),
        ),
    ]
