# Generated by Django 6.0.4 on 2026-08-26 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationDroits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('type_contrat', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('Stage_Qualification', 'Stage de Qualification')], max_length=50)),
                ('motif_rupture', models.CharField(choices=[('Demission', 'Démission'), ('Licenciement_Sans_Faute', 'Licenciement Sans Faute'), ('Licenciement_Faute_Lourde', 'Licenciement Faute Lourde'), ('Licenciement_Eco', 'Licenciement Économique'), ('Fin_CDD', 'Fin de CDD'), ('Rupture_Anticipee_CDD', 'Rupture Anticipée CDD'), ('Retraite', 'Retraite'), ('Deces', 'Décès')], max_length=50)),
                ('categorie_pro', models.CharField(choices=[('Ouvrier_Manoeuvre', 'Ouvrier / Manœuvre'), ('Employe_Qualifie', 'Employé Qualifié'), ('Agent_Maitrise', 'Agent de Maîtrise'), ('Cadre_Assimile', 'Cadre et Assimilé')], max_length=50)),
                ('date_embauche', models.DateField(help_text='Date de début de contrat')),
                ('date_rupture', models.DateField(help_text='Date de fin effective du contrat')),
                ('salaire_base', models.DecimalField(decimal_places=2, help_text='Salaire de base mensuel en FCFA', max_digits=12)),
                ('surtaux_accords', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('salaires_12_mois', models.JSONField(default=list, help_text='Historique des 12 derniers salaires bruts perçus')),
                ('preavis_effectue', models.BooleanField(default=False)),
                ('jours_conges_acquis', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
