# Generated by Django 6.0.5 on 2026-08-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawcalcul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationdroits',
            name='motif_rupture',
            field=models.CharField(choices=[('Demission', 'Démission'), ('Licenciement_Sans_Faute', 'Licenciement Sans Faute'), ('Licenciement_Faute_Lourde', 'Licenciement Faute Lourde'), ('Licenciement_Eco', 'Licenciement Économique'), ('Fin_CDD', 'Fin de CDD'), ('Commun_Accord_CDD', "Rupture d'un commun accord"), ('Rupture_Anticipee_Employe', "Rupture anticipée par l'employé"), ('Rupture_Anticipee_Employeur', "Rupture anticipée abusive par l'employeur"), ('Faute_Lourde_CDD', 'Rupture pour faute lourde'), ('Retraite', 'Retraite'), ('Deces', 'Décès')], max_length=50),
        ),
    ]
