# Generated by Django 6.0.4 on 2026-09-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawcalcul', '0002_alter_simulationdroits_motif_rupture'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationdroits',
            name='cdd_transforms_to_cdi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulationdroits',
            name='is_trial_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='simulationdroits',
            name='motif_rupture',
            field=models.CharField(choices=[('Demission', 'Démission'), ('Licenciement_Sans_Faute', 'Licenciement Sans Faute'), ('Licenciement_Faute_Lourde', 'Licenciement Faute Lourde'), ('Licenciement_Eco', 'Licenciement Économique'), ('Fin_CDD', 'Fin de CDD'), ('Commun_Accord_CDD', "Rupture d'un commun accord"), ('Rupture_Anticipee_Employe', "Rupture anticipée par l'employé"), ('Rupture_Anticipee_Employeur', "Rupture anticipée abusive par l'employeur"), ('Faute_Lourde_CDD', 'Rupture pour faute lourde'), ('Licenciement_Abusif', 'Licenciement Abusif'), ('Commun_Accord_CDI', "Rupture d'un commun accord (CDI)"), ('Maladie_Longue_Duree', 'Maladie longue durée'), ('Force_Majeure', 'Force Majeure'), ('Retraite', 'Retraite'), ('Deces', 'Décès')], max_length=50),
        ),
    ]
