# Generated by Django 6.0.4 on 2026-09-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawcalcul', '0003_simulationdroits_cdd_transforms_to_cdi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationdroits',
            name='employer_damages',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='simulationdroits',
            name='remaining_months',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
