# Generated by Django 6.0.4 on 2026-06-22 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0004_pack'),
        ('ecommerce', '0001_initial'),
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='pro.legalprofessional'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='pro.legalprofessional'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pro_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='contrat.contrat'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='contrat.contrat'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='contrat_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contrat__isnull', False), ('pro__isnull', True)), models.Q(('contrat__isnull', True), ('pro__isnull', False)), _connector='OR'), name='cartitem_contrat_or_pro_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contrat__isnull', False), ('pro__isnull', True)), models.Q(('contrat__isnull', True), ('pro__isnull', False)), _connector='OR'), name='orderitem_contrat_or_pro_exclusive'),
        ),
    ]
