# Generated by Django 6.0.5 on 2026-06-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='user_inputs',
            field=models.JSONField(blank=True, default=dict, help_text='Stock les variables saisies par le client pour générer le contrat', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user_inputs',
            field=models.JSONField(blank=True, default=dict, help_text='Stock les variables saisies par le client pour générer le contrat', null=True),
        ),
    ]
