# Generated by Django 6.0.4 on 2026-07-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_cartitem_user_inputs_orderitem_user_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text="Nombre de fois que l'acheteur a télécharger le contrat"),
        ),
    ]
