# Generated by Django 6.0.4 on 2026-07-07 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0007_alter_category_description_customedcontract'),
        ('ecommerce', '0004_order_download_count'),
        ('pro', '0003_legalprofessional_visiting_card'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='cartitem_contrat_or_pro_exclusive',
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='orderitem_contrat_or_pro_exclusive',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='customed_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customed_contract_items', to='contrat.customedcontract'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='contrat_customed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contrat.customedcontract'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customised_contract',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contrat__isnull', False), ('customed_contract__isnull', True), ('pro__isnull', True)), models.Q(('contrat__isnull', True), ('customed_contract__isnull', True), ('pro__isnull', False)), models.Q(('contrat__isnull', True), ('customed_contract__isnull', False), ('pro__isnull', True)), _connector='OR'), name='cartitem_exclusive_type'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contrat__isnull', False), ('contrat_customed__isnull', True), ('pro__isnull', True)), models.Q(('contrat__isnull', True), ('contrat_customed__isnull', True), ('pro__isnull', False)), models.Q(('contrat__isnull', True), ('contrat_customed__isnull', False), ('pro__isnull', True)), _connector='OR'), name='orderitem_exclusive_type'),
        ),
    ]
