# Generated by Django 6.0.4 on 2026-07-13 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0010_remove_pack_customer_alter_pack_is_active_userpack'),
        ('ecommerce', '0005_remove_cartitem_cartitem_contrat_or_pro_exclusive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='packs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packs_items', to='contrat.pack'),
        ),
    ]
