# Generated by Django 6.0.4 on 2026-07-14 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0010_remove_pack_customer_alter_pack_is_active_userpack'),
        ('ecommerce', '0006_cartitem_packs'),
        ('pro', '0003_legalprofessional_visiting_card'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='cartitem_exclusive_type',
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='orderitem_exclusive_type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='contrat.pack'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pack_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contrat__isnull', False), ('customed_contract__isnull', True), ('packs__isnull', True), ('pro__isnull', True)), models.Q(('contrat__isnull', True), ('customed_contract__isnull', True), ('packs__isnull', True), ('pro__isnull', False)), models.Q(('contrat__isnull', True), ('customed_contract__isnull', False), ('packs__isnull', True), ('pro__isnull', True)), models.Q(('contrat__isnull', True), ('customed_contract__isnull', True), ('packs__isnull', False), ('pro__isnull', True)), _connector='OR'), name='cartitem_exclusive_type'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contrat__isnull', False), ('contrat_customed__isnull', True), ('pack__isnull', True), ('pro__isnull', True)), models.Q(('contrat__isnull', True), ('contrat_customed__isnull', True), ('pack__isnull', True), ('pro__isnull', False)), models.Q(('contrat__isnull', True), ('contrat_customed__isnull', False), ('pack__isnull', True), ('pro__isnull', True)), models.Q(('contrat__isnull', True), ('contrat_customed__isnull', True), ('pack__isnull', False), ('pro__isnull', True)), _connector='OR'), name='orderitem_exclusive_type'),
        ),
    ]
