# Generated by Django 6.0.4 on 2026-08-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0018_contractrevision'),
        ('ecommerce', '0008_coupon_order_discount_amount_cart_coupon_and_more'),
        ('pro', '0004_procarddownload'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='cartitem_exclusive_type',
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='orderitem_exclusive_type',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='contract_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='contrat.contractrevision'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='contract_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='contrat.contractrevision'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='revision_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contract_revision__isnull', True), ('contrat__isnull', False), ('customed_contract__isnull', True), ('packs__isnull', True), ('pro__isnull', True)), models.Q(('contract_revision__isnull', True), ('contrat__isnull', True), ('customed_contract__isnull', True), ('packs__isnull', True), ('pro__isnull', False)), models.Q(('contract_revision__isnull', True), ('contrat__isnull', True), ('customed_contract__isnull', False), ('packs__isnull', True), ('pro__isnull', True)), models.Q(('contract_revision__isnull', True), ('contrat__isnull', True), ('customed_contract__isnull', True), ('packs__isnull', False), ('pro__isnull', True)), models.Q(('contract_revision__isnull', False), ('contrat__isnull', True), ('customed_contract__isnull', True), ('packs__isnull', True), ('pro__isnull', True)), _connector='OR'), name='cartitem_exclusive_type'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contract_revision__isnull', True), ('contrat__isnull', False), ('contrat_customed__isnull', True), ('pack__isnull', True), ('pro__isnull', True)), models.Q(('contract_revision__isnull', True), ('contrat__isnull', True), ('contrat_customed__isnull', True), ('pack__isnull', True), ('pro__isnull', False)), models.Q(('contract_revision__isnull', True), ('contrat__isnull', True), ('contrat_customed__isnull', False), ('pack__isnull', True), ('pro__isnull', True)), models.Q(('contract_revision__isnull', True), ('contrat__isnull', True), ('contrat_customed__isnull', True), ('pack__isnull', False), ('pro__isnull', True)), models.Q(('contract_revision__isnull', False), ('contrat__isnull', True), ('contrat_customed__isnull', True), ('pack__isnull', True), ('pro__isnull', True)), _connector='OR'), name='orderitem_exclusive_type'),
        ),
    ]
