# Generated by Django 6.0.4 on 2026-09-07 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_cartitem_cartitem_exclusive_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='order_user_or_guest_exclusive',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest__isnull', True), ('user__isnull', False)), models.Q(('guest__isnull', False), ('user__isnull', True)), models.Q(('guest__isnull', True), ('user__isnull', True)), _connector='OR'), name='order_user_or_guest_exclusive'),
        ),
    ]
