# Generated by Django 6.0.4 on 2026-09-09 10:39

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default=account.models.generate_short_token, editable=False, max_length=6, unique=True),
        ),
    ]
