# Generated by Django 6.0.4 on 2026-06-22 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du pays')),
                ('code', models.CharField(help_text='Code ISO (ex: CI, SN, CM)', max_length=5, unique=True)),
                ('is_ohada_member', models.BooleanField(default=True, verbose_name="Membre de l'espace OHADA")),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegalDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name="Domaine d'expertise")),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Domaine du droit (ou Acte Uniforme)',
                'verbose_name_plural': 'Domaines du droit',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegalProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('title', models.CharField(choices=[('AVOCAT', 'Avocat'), ('NOTAIRE', 'Notaire'), ('CONSEIL_JURIDIQUE', 'Conseil Juridique et Fiscal'), ('JURISTE', "Juriste d'entreprise"), ('HUISSIER', 'Huissier de justice'), ('MANDATAIRE', 'Mandataire Judiciaire / Syndic'), ('EXPERT_COMPTABLE', 'Expert-Comptable / Commissaire aux comptes'), ('AUTRE', 'Autre professionnel du droit')], max_length=50, verbose_name='Titre professionnel')),
                ('professional_order', models.CharField(blank=True, help_text="Ex: Barreau de Côte d'Ivoire, Ordre des Notaires du Sénégal...", max_length=150, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'inscription à l'ordre")),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web / LinkedIn')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='professionals/profiles/', verbose_name='Photo de profil')),
                ('bio', models.TextField(verbose_name='Biographie / Présentation')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('city', models.CharField(max_length=100, verbose_name="Ville d'exercice (ex: Abidjan, Dakar, Douala)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Profil actif')),
                ('is_verified', models.BooleanField(default=False, help_text="Cocher si Contratchap a vérifié l'identité et l'inscription à l'ordre de ce professionnel.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professionals', to='pro.country', verbose_name="Pays d'exercice")),
                ('domains', models.ManyToManyField(related_name='professionals', to='pro.legaldomain', verbose_name="Domaines d'expertise (Actes Uniformes, etc.)")),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Professionnel de l'espace OHADA",
                'verbose_name_plural': "Professionnels de l'espace OHADA",
                'ordering': ['-is_verified', '-created_at'],
            },
        ),
    ]
