# Generated by Django 6.0.4 on 2026-06-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_alter_legalprofessional_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalprofessional',
            name='visiting_card',
            field=models.FileField(blank=True, null=True, upload_to='professionals/visiting_cards'),
        ),
    ]
