# Generated by Django 6.0.4 on 2026-07-22 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_legalprofessional_visiting_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProCardDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='pro.legalprofessional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_card_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pro')},
            },
        ),
    ]
