# Generated by Django 6.0.5 on 2026-05-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contrat',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
