# Generated by Django 6.0.5 on 2026-05-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0002_contrat_downloads_contrat_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='contrat_images/'),
        ),
    ]
