# Generated by Django 6.0.4 on 2026-07-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0004_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
