# Generated by Django 6.0.4 on 2026-07-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0005_contrat_promo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
