# Generated by Django 6.0.4 on 2026-07-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0007_alter_category_description_customedcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='customedcontract',
            name='promo_price',
            field=models.FloatField(default=0.0),
        ),
    ]
