# Generated by Django 6.0.4 on 2026-07-13 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0009_pack_customer_pack_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='customer',
        ),
        migrations.AlterField(
            model_name='pack',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchasers', to='contrat.pack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_packs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
