# Generated by Django 6.0.4 on 2026-07-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0010_remove_pack_customer_alter_pack_is_active_userpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='consultation_pro_incluse',
            field=models.BooleanField(default=False, help_text='Cochez si ce pack offre une mise en relation/consultation gratuite avec un pro.'),
        ),
        migrations.AddField(
            model_name='pack',
            name='duree_validite_jours',
            field=models.PositiveIntegerField(default=365, help_text='Durée de validité du pack en jours (ex: 365 pour 1 an).'),
        ),
        migrations.AddField(
            model_name='pack',
            name='nombre_credits',
            field=models.PositiveIntegerField(default=0, help_text="Nombre de contrats au choix que l'utilisateur pourra débloquer gratuitement."),
        ),
        migrations.AddField(
            model_name='pack',
            name='remise_sur_mesure',
            field=models.PositiveIntegerField(default=0, help_text="Pourcentage de réduction sur les requêtes 'CustomedContract' (ex: 20 pour 20%)"),
        ),
        migrations.AlterField(
            model_name='pack',
            name='contrats',
            field=models.ManyToManyField(blank=True, help_text="Les contrats spécifiques inclus d'office dans ce pack.", related_name='packs', to='contrat.contrat'),
        ),
    ]
