# Generated by Django 6.0.4 on 2026-07-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0011_pack_consultation_pro_incluse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpack',
            name='contrats_choisis',
            field=models.ManyToManyField(blank=True, help_text="Les contrats que l'utilisateur a choisi de débloquer avec ses crédits.", to='contrat.contrat'),
        ),
        migrations.AddField(
            model_name='userpack',
            name='credits_restants',
            field=models.PositiveIntegerField(default=0, help_text="Combien de crédits il reste à l'utilisateur pour ce pack."),
        ),
        migrations.AddField(
            model_name='userpack',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
