# Generated by Django 6.0.4 on 2026-07-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0012_userpack_contrats_choisis_userpack_credits_restants_and_more'),
        ('pro', '0004_procarddownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpack',
            name='cartes_pro_restantes',
            field=models.PositiveIntegerField(default=0, help_text='Combien de cartes de pro il reste à télécharger pour ce pack.'),
        ),
        migrations.AddField(
            model_name='userpack',
            name='pros_debloques',
            field=models.ManyToManyField(blank=True, help_text='Les professionnels dont la carte a déjà été débloquée avec ce pack.', related_name='debloque_par', to='pro.legalprofessional'),
        ),
    ]
