# Generated by Django 6.0.4 on 2026-07-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0013_userpack_cartes_pro_restantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='nombre_cartes_pro',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de cartes de visite de professionnels téléchargeables avec ce pack (1 pour le pack Basique, plus pour les offres supérieures).'),
        ),
    ]
