# Generated by Django 6.0.4 on 2026-07-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0014_pack_nombre_cartes_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='remise_sur_mesure',
        ),
        migrations.AddField(
            model_name='pack',
            name='custom_contract_included',
            field=models.BooleanField(default=False, help_text='Inclusion des contrats sur mesure'),
        ),
        migrations.AddField(
            model_name='pack',
            name='nombre_customed_contract',
            field=models.IntegerField(default=0, help_text='Nombre de contrat personnalisé'),
        ),
    ]
