# Generated by Django 6.0.4 on 2026-07-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0015_remove_pack_remise_sur_mesure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpack',
            name='customs_restants',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de contrats sur mesure restants à utiliser pour ce pack.'),
        ),
    ]
