# Generated by Django 6.0.4 on 2026-07-24 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0016_userpack_customs_restants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customedcontract',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customed_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customedcontract',
            name='user_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customed_contracts', to='contrat.userpack'),
        ),
    ]
