# Generated by Django 6.0.4 on 2026-08-03 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0017_customedcontract_user_customedcontract_user_pack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(help_text='Titre ou nature du contrat à réviser', max_length=225)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('client_instructions', models.TextField(help_text='Ce que le client souhaite que vous vérifiiez spécifiquement')),
                ('original_file', models.FileField(help_text='Le contrat envoyé par le client', upload_to='revisions/originals/')),
                ('revised_file', models.FileField(blank=True, help_text='Le contrat révisé et renvoyé par vos juristes', null=True, upload_to='revisions/completed/')),
                ('price', models.FloatField(default=15000.0)),
                ('promo_price', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours de révision'), ('COMPLETED', 'Terminé'), ('REJECTED', 'Rejeté / Annulé')], default='PENDING', max_length=20)),
                ('is_revised', models.BooleanField(default=False)),
                ('expert_comments', models.TextField(blank=True, help_text='Notes laissées par le juriste après révision', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_revisions', to=settings.AUTH_USER_MODEL)),
                ('user_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_revisions', to='contrat.userpack')),
            ],
        ),
    ]
