# Generated by Django 6.0.4 on 2026-08-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0018_contractrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='customedcontract',
            name='final_document',
            field=models.FileField(blank=True, help_text='PDF final rédigé, uploadé par le juriste une fois terminé.', null=True, upload_to='customed_contracts/completed/'),
        ),
    ]
