# Generated by Django 6.0.4 on 2026-08-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0019_customedcontract_final_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='prix_promo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]